# Generated by Django 4.2.6 on 2023-10-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('companylogo', models.ImageField(upload_to='')),
                ('level', models.IntegerField()),
                ('duration', models.CharField(max_length=100)),
            ],
        ),
    ]
