# Generated by Django 4.2.6 on 2023-12-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='duration',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='level',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='salary',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='companylogo',
            field=models.URLField(),
        ),
    ]
