# Generated by Django 5.0.2 on 2024-03-18 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0004_passwordresettoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
